gitignore = [
    ".venv/",
    "uv.lock"
]

[metadata]
type = "uv"
role = "package_manager"
description = "uv - An extremely fast Python package installer and resolver"
required_tools = ["uv"]
manifest_file = "pyproject.toml"

[scripts]
install = "uv sync"
install_pkg = "uv add"
remove_pkg = "uv remove"
run = "uv run"

[env]
VIRTUAL_ENV = "${MNGPROJ_COMPONENT_ROOT}/.venv"
