gitignore = [
    "node_modules/",
    "build/",
    "dist/",
    ".env.local"
]

[metadata]
type = "react"
role = "framework"
description = "React JS Framework"
required_tools = ["npm"]

[scripts]
start = "npm start"
build = "npm run build"
test = "npm test"
eject = "npm run eject"
run = "npm start"