gitignore = [
    "*.o",
    "*.out",
    "compile_commands.json",
    ".cache/"
]

[metadata]
type = "clang"
role = "language"
description = "C/C++ with Clang"
required_tools = ["clang"]

[scripts]
build = "clang -o app main.c"
run = "./app"
clean = "rm -f app *.o"