gitignore = [
    "*.o",
    "a.out"
]

[metadata]
type = "gcc"
role = "language"
description = "C/C++ with GCC"
required_tools = ["gcc"]

[scripts]
build = "gcc -o app main.c"
run = "./app"
clean = "rm -f app *.o"