gitignore = [
    "/bin/",
    "*.exe",
    "*.dll",
    "*.so",
    "*.dylib",
    "*.test",
    "*.out",
    "vendor/"
]

[metadata]
type = "go"
role = "language"
description = "Go Programming Language"
required_tools = ["go"]

[scripts]
run = "go run ."
build = "go build -o dist/app ."
test = "go test ./..."
lint = "go vet ./..."

[env]

GOPATH = "${MNGPROJ_COMPONENT_ROOT}/.go"
