gitignore = [
    "__pycache__/",
    "*.py[cod]",
    "*$py.class"
]

[metadata]
type = "python"
role = "language"
description = "Python Programming Language"
required_tools = ["python"]

[scripts]
run = "python main.py"
test = "python -m unittest"

[env]
PYTHONUNBUFFERED = "1"