gitignore = [
    "dist/",
    "built/",
    "tsconfig.tsbuildinfo"
]

[metadata]
type = "ts"
role = "language"
description = "TypeScript Language"
required_tools = ["tsc"]

[scripts]
build = "tsc"
run = "ts-node index.ts"
test = "ts-node test.ts"